name: publish to jfrog

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: jfrog/setup-jfrog-cli@v3
env:
   # JFrog platform url (for example: https://acme.jfrog.io) 
      JF_URL: ${{  }}

    # Basic authentication credentials
      JF_USER: ${{ secrets.shnavi002@gmail.com }}
      JF_PASSWORD: ${{ secrets.Naveen.@1991 }}
